story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('websitegue.urls')),
]

websitegue/urls.py
from django.urls import path

from . import views

app_name = 'websitegue'
urlpatterns = [
    path('', views.index, name="Home"),
    path('/profile',views.profile, name="Profile"),
    path('/experiences',views.experiences, name="Experiences"),
    path('/skills',views.skills, name="Skills")
]

websitegue/models.py
from django.db import models

# Create your models here.

websitegue/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'home.html')

def profile(request):
    return render(request, 'profile.html')

def experiences(request):
    return render(request, 'experiences.html')

def skills(request):
    return render(request, 'skills.html')

websitegue/templates/experiences.html
<!doctype html>
<html lang="en">
    <head>
        {% load staticfiles %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static 'css/index.css' %}">

        <link rel="icon" href="{% static 'image/saxophone.png' %}">
        
        <title>Website Gue</title>
    </head>
    <body class="bg">
        <div class="row desc">
            <div class="container-fluid">
                    <div class="col-md-12">
                        <a href="{% url 'websitegue:Home'%}">
                            <img class="home" src="{% static 'image/house.png' %}" title="Home" alt="home">
                        </a>
                        <a href="{% url 'websitegue:Profile'%}" class="btn btn-info" role="button">PROFILE</a>
                        <a href="{% url 'websitegue:Experiences'%}" class="btn btn-info" role="button">EXPERIENCES</a>
                        <a href="{% url 'websitegue:Skills'%}" class="btn btn-info" role="button">SKILLS</a>
                    </div>
                </div>
            <div class="col-md-12">
                <h1>EXPERIENCES</h1>
            </div>
            <div class="col-md-12">
                <pre class="datadiri">

       Kepanitiaan : 

       - Ketua panitia kebaktian gabungan rohani kristen 34 tahun 2017

       - Ketua panitia acara Newbie Cup tahun 2019

       - Staff keamanan High School Celebration tahun 2017

       - Staff keamanan Olim UI tahun 2018

       - Staff TnV Compfest Fasilkom tahun 2019

       - Staff Sponsorship High School Celebration tahun 2016

       - Staff Humas CGT tahun 2018
 
       - PJ kontingen band UIAW
 

       Organisasi :

       - BEM Seni budaya Fasilkom

       - BPH Humas Rohani Kristen 34

       - Gazper XIX

       - Personil band Diverse

       - Personil band Nibels

       - Personil band Glazzy Tunes

       - Personil band Blue Cirrus
                </pre>
            </div>
        </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

websitegue/templates/home.html
<!doctype html>
<html lang="en">
    <head>
        {% load staticfiles %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static 'css/index.css' %}">

        <link rel="icon" href="{% static 'image/saxophone.png' %}">

        <title>Website Gue</title>
    </head>
    <body class="bg">
        <div>
            <img class="rounded-circle" alt="avatar" src="{% static 'image/foto.png' %}">
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <p class="nama">JACOB MARULITUA IDO SITUMORANG</p>
                </div>
                <div class="col-md-2"></div>
                <div class="col-md-12">
                    <a href="{% url 'websitegue:Profile'%}" class="btn btn-info" style="margin:10px;" role="button">PROFILE</a>
                    <a href="{% url 'websitegue:Experiences'%}" class="btn btn-info" style="margin:10px;" role="button">EXPERIENCES</a>
                    <a href="{% url 'websitegue:Skills'%}" class="btn btn-info" style="margin:10px;" role="button">SKILLS</a>
                </div>
                <div class="col-md-12">
                        <a href="https://www.instagram.com/jacobstmrg/?hl=en">
                            <img class="social" src="{% static 'image/instagram-logo.png' %}" title="Instagram" alt="ig">
                        </a>
                        <a href="https://twitter.com/SitumorangJacob">
                            <img class="social" src="{% static 'image/twitter.png' %}" title="Twitter" alt="twitter">
                        </a>
                        <a href="https://wa.me/+6281212139002">
                            <img class="social" src="{% static 'image/whatsapp-logo.png' %}" title="WhatsApp" alt="wa">
                        </a>
                        <a href="https://id-id.facebook.com/jacob.zc.9">
                            <img class="social" src="{% static 'image/facebook-logo.png' %}" title="Facebook" alt="facebook">
                        </a>
                </div>  
            </div>
        </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

websitegue/templates/profile.html
<!doctype html>
<html lang="en">
    <head>
        {% load staticfiles %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static 'css/index.css' %}">

        <link rel="icon" href="{% static 'image/saxophone.png' %}">
        
        <title>Website Gue</title>
    </head>
    <body class="bg">
        <div class="row desc">
            <div class="container-fluid">
                <div class="col-md-12">
                    <a href="{% url 'websitegue:Home' %}">
                        <img class="home" src="{% static 'image/house.png' %}" title="Home" alt="home">
                    </a>
                    <a href="{% url 'websitegue:Profile' %}" class="btn btn-info"  role="button">PROFILE</a>
                    <a href="{% url 'websitegue:Experiences' %}" class="btn btn-info"  role="button">EXPERIENCES</a>
                    <a href="{% url 'websitegue:Skills'%}" class="btn btn-info"  role="button">SKILLS</a>
                </div>
            </div>
            <div class="col-md-12">
                <h1>PROFILE</h1>
            </div>
            <div class="col-md-7">
                <pre class="datadiri">

       Nama Panggilan    : Jacob 

       Tanggal Lahir        : 8 May 2000

       Pendidikan            : S1 Sistem Informasi - 
                                       Universitas Indonesia

       Agama                  : Kristen Protestan

       Email                   : Jacobzc77@gmail.com

       Jenis Kelamin        : Pria

       NPM                    : 1806185361

       No. telp                : 081212139002

       Status                  : Belum Menikah
                </pre>
            </div>
                <div class="col-md-5">
                    <img class="fotoui" src="{% static 'image/ui.jpg' %}" title="ui" alt="ui">
                </div>
        </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

websitegue/templates/skills.html
<!doctype html>
<html lang="en">
    <head>
        {% load staticfiles %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static 'css/index.css' %}">

        <link rel="icon" href="{% static 'image/saxophone.png' %}">
        
        <title>Website Gue</title>
    </head>
    <body class="bg">
        <div class="row desc">
            <div class="container-fluid">
                <div class="col-md-12">
                    <a href="{% url 'websitegue:Home'%}">
                        <img class="home" src="{% static 'image/house.png' %}" title="Home" alt="home">
                    </a>
                    <a href="{% url 'websitegue:Profile'%}" class="btn btn-info" role="button">PROFILE</a>
                    <a href="{% url 'websitegue:Experiences'%}" class="btn btn-info" role="button">EXPERIENCES</a>
                    <a href="{% url 'websitegue:Skills'%}" class="btn btn-info" role="button">SKILLS</a>
                </div>
            </div>
        <div class="col-md-12">
            <h1>SKILLS</h1>
        </div>
        <div class="container">
            <div class="bar front expert" data-skill="MUSIC"></div>
            <div class="bar back basic" data-skill="PROGRAMMING"></div>
            <div class="bar front advanced" data-skill="SOCIAL"></div>
            <div class="bar back intermediate" data-skill="LEADERSHIP"></div>
            <div class="bar front advanced" data-skill="TEAMWORK"></div>
            <div class="bar back basic" data-skill="MARKETING"></div>
            <div class="bar back intermediate" data-skill="PROBLEM_SOLVING"></div>
        </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>